### ISSUE TITLE
Add tick source

### ISSUE THREAD

**Issue by bloodmc** [ArclightPowered/api#1]
This is a request for support in adding API into retrieving the current ticking block, entity, or tileentity. 
This will allow protection plugins, such as `GriefDefender`, to provide event causes where no source information exists within the event. 
An example for this use case is with the mod Pixelmon. When a player throws a pokeball, the EntitySpawnEvent just passes the standard `SpawnReason.DEFAULT` which is also what is passed for natural spawns. If I am able to query Arclight for the ticking projectile then I can pass the projectile as a source instead and thus allow admins the ability to control spawns based on a proper source.

If you need any more details, let me know.

Thanks!

**Comment by IzzelAliz** [comment]
What would you expect for this api? Is a simple `org.bukkit.entity.Entity getTickingEntity()` enough for this use case, or maybe a Sponge like cause tracking system?

**Comment by bloodmc** [comment]
`org.bukkit.entity.Entity getTickingEntity()` would only provide the current ticking entity. I would need the ability to retrieve the current ticking block and tileentity as well.

As for how to handle it in API, perhaps a simple TickTracker interface that provides the following methods to start it off
```java
    /**
     * Retrieves the current ticking source.
     *
     * @return The current ticking source
     */
    Object getTickingSource();

    /**
     * Retrieves the current ticking {@link Entity}.
     *
     * @return The current ticking entity, if available
     */
    @Nullable Entity getTickingEntity();

    /**
     * Retrieves the current ticking {@link Block}.
     *
     * @return The current ticking block, if available
     */
    @Nullable Block getTickingBlock();

    /**
     * Retrieves the current ticking {@link TileState}.
     *
     * @return The current ticking tile state, if available
     */
    @Nullable TileState getTickingTileState();
```

I don't think you need a CauseTracker system like Sponge. Users that need that can just use Sponge. It makes more sense to stay simple for performance reasons and to expand as needed.

Feel free to provide me with a DEV build so I can confirm everything works as expected before pushing an update to API unless you want to push a `dev` branch for testing this.

Thanks!

**Comment by IzzelAliz** [comment]
Now there's an API draft #2 for this. The `getTickingSource` seems confusing to me, so it is not added.

**Comment by IzzelAliz** [comment]
And [here](https://oneindex.conchservices.com/api/raw/?path=/ticking-source-draft-arclight-forge-1.16.5-1.0.24-SNAPSHOT.jar) is a 1.16.5 build implementing this draft api for you to test. The API can be found at https://maven.izzel.io/releases `io.izzel.arclight:arclight-api:1.4.0-SNAPSHOT`

**Comment by bloodmc** [comment]
`[com.griefdefender.listener.EntityEventHandler:handleEntitySpawn:905]: Ticking entity = ArclightModProjectile{PIXELMON_OCCUPIED_POKEBALL}`

Seems to work for pixelmon projectiles now during the spawn event.

As for `getTickingSource()`, this should provide the current block, entity, or tileentity that is ticking (if any)

It actually should be nullable as well
```java
@Nullable Object getTickingSource();
```

The purpose of this method is so I can simply check if there are any ticking sources when needed rather than calling all 3 methods.

**Comment by bloodmc** [comment]
I didn't realize this would be pushed to master so soon =)

Had a few more ideas now that I reviewed more of the implementation. Since Arclight is already injecting its own interfaces for Entity to implement, how about doing the same for `TileEntity`? This would allow the TE to be returned directly instead of grabbing the `BlockState` and checking for `TileState`. You would just need to expose the TE interface to Arclight API. 
Let me know what you think.

Thanks!

**Comment by IzzelAliz** [comment]
Thank you for your review.

The CraftBlock object and its subclass is a snapshot of actual block, which is not designed to cache and return it. Doing the same as the Entity implementation do not make sense, while it is hard to synchronize this snapshot with actual block entity.

```java
public class CraftBlockEntityState<T extends TileEntity> extends CraftBlockState implements TileState {
    private final Class<T> tileEntityClass;
    private final T tileEntity;
    private final T snapshot;
}
```

**Comment by bloodmc** [comment]
I am referring to this line

https://github.com/IzzelAliz/Arclight/blob/1.16/arclight-common/src/main/java/io/izzel/arclight/common/mod/server/api/DefaultTickingTracker.java#L61

If you injected your own interface into `TileEntity` then you could just return the TE directly. There would be no need to worry about `CraftBlockEntityState` as it wouldn't be used. If a plugin accessing API really needed the `TileState` then they could request it normally. As for my use case, I just need the identifier and location for event cause.

Ex.

```java
    @Nullable
    @Override
    public ArclightBlockEntity getTickingBlockEntity() {
        TileEntity tileEntity = ArclightCaptures.getTickingTileEntity();
        if (tileEntity != null) {
            return (ArclightBlockEntity) tileEntity;
        }
        return null;
    }
```

This could also just be an added method to the `TickingTracker`. 

Just a thought =). The current implementation will still work fine.

**Comment by IzzelAliz** [comment]
Then it would be better just returning a Location or a Block here, since they are rather "light" objects.

**Comment by bloodmc** [comment]
Well my plugin's use case is to obtain the proper identifier of the source. A location or block would not always provide that for a modded `TileEntity`. I would be required to perform an additional lookup for that information. 

However, the current implementation works for my needs as I can simply query what I need from the TileState that is passed. I just wanted to point out another possible idea =)
Lets keep it as is for now and I'll report back if I run into any issues.
